# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgamma_rcpp <- function(x, mu, sigma) {
    .Call('moveHMM_dgamma_rcpp', PACKAGE = 'moveHMM', x, mu, sigma)
}

dweibull_rcpp <- function(x, shape, scale) {
    .Call('moveHMM_dweibull_rcpp', PACKAGE = 'moveHMM', x, shape, scale)
}

dlnorm_rcpp <- function(x, meanlog, sdlog) {
    .Call('moveHMM_dlnorm_rcpp', PACKAGE = 'moveHMM', x, meanlog, sdlog)
}

dexp_rcpp <- function(x, rate, foo = 0) {
    .Call('moveHMM_dexp_rcpp', PACKAGE = 'moveHMM', x, rate, foo)
}

dvm_rcpp <- function(x, mu, kappa) {
    .Call('moveHMM_dvm_rcpp', PACKAGE = 'moveHMM', x, mu, kappa)
}

dwrpcauchy_rcpp <- function(x, mu, rho) {
    .Call('moveHMM_dwrpcauchy_rcpp', PACKAGE = 'moveHMM', x, mu, rho)
}

nLogLike_rcpp <- function(nbStates, beta, covs, data, stepDist, angleDist, stepPar, anglePar, delta, aInd, zeroInflation = FALSE, stationary = FALSE) {
    .Call('moveHMM_nLogLike_rcpp', PACKAGE = 'moveHMM', nbStates, beta, covs, data, stepDist, angleDist, stepPar, anglePar, delta, aInd, zeroInflation, stationary)
}

trMatrix_rcpp <- function(nbStates, beta, covs) {
    .Call('moveHMM_trMatrix_rcpp', PACKAGE = 'moveHMM', nbStates, beta, covs)
}

