# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allProbs_rcpp <- function(data, nbStates, stepDist, angleDist, stepPar, anglePar, zeroInflation = FALSE) {
    .Call('moveHMM_allProbs_rcpp', PACKAGE = 'moveHMM', data, nbStates, stepDist, angleDist, stepPar, anglePar, zeroInflation)
}

nLogLike_rcpp <- function(trVec, delta, allProbs) {
    .Call('moveHMM_nLogLike_rcpp', PACKAGE = 'moveHMM', trVec, delta, allProbs)
}

trMatrix_rcpp <- function(nbStates, beta, covs) {
    .Call('moveHMM_trMatrix_rcpp', PACKAGE = 'moveHMM', nbStates, beta, covs)
}

